### ISSUE TITLE
segfault with 0.4.17

### ISSUE THREAD

**Issue by cs01** [python-greenlet/greenlet#194] opened 2020-10-03 05:52 UTC
Reported in https://github.com/cs01/gdbgui/issues/353
Fixed in https://github.com/cs01/gdbgui/pull/354 by downgrading to 0.4.16

Repro:
```
> pip install gdbgui==0.14.0.0
> gdbgui
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
Opening gdbgui with default browser at http://127.0.0.1:5000
View gdbgui dashboard at http://127.0.0.1:5000/dashboard
exit gdbgui by pressing CTRL+C
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
Segmentation fault: 11
```

```
> pip freeze
Brotli==1.0.9
click==7.1.2
dnspython==2.0.0
eventlet==0.25.2
Flask==0.12.5
Flask-Compress==1.5.0
Flask-SocketIO==2.9.6
gdbgui==0.14.0.0
gevent==1.5.0
gevent-websocket==0.10.1
greenlet==0.4.17
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
monotonic==1.5
pygdbmi==0.10.0.0
Pygments==2.7.1
python-engineio==3.13.2
python-socketio==4.6.0
six==1.15.0
Werkzeug==0.16.1
```

**Comment by jamadden** [comment] 2020-10-03 12:50
Duplicate of #178.

**Closed by jamadden** 2020-10-03 12:50 UTC
