### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [python-greenlet/greenlet#202] opened 2020-11-02 09:35 UTC
**Summary**
Installing greenlet on aarch64 via pip using command "pip3 install greenlet" tries to build wheel from source code.

**Problem description**
greenlet doesn't have wheel for aarch64 on PyPI repository. So, while installing greenlet via pip on aarch64, pip builds wheel for same resulting in it takes more time to install greenlet. Making wheel available for aarch64 will benefit aarch64 users by minimizing greenlet installation time.

**Expected Output**
Pip should be able to download greenlet wheel from PyPI repository rather than building it from source code.

@greenlet-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make greenlet wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by jamadden** [comment] 2020-11-11 21:59
Thanks for the request. This is a duplicate of #175 and is being handled as part of ongoing packaging changes.

**Closed by jamadden** 2020-11-11 21:59 UTC
