### ISSUE TITLE
greenlet 0.4.17 breaks gevent (which breaks bottle)

### ISSUE THREAD

**Issue by CrimsonGlory** [python-greenlet/greenlet#195] opened 2020-10-06 03:49 UTC
Maybe this is not the best place to post it.
In python python:3.8.2-buster, the update from 0.4.16 to 0.4.17 broke gevent 20.5.0, which broke bottle 0.12.18.
```
2020-10-01T20:13:07+00:00 172.18.0.1 api[1217]: Bottle v0.12.18 server starting up (using GeventServer())...
2020-10-01T20:13:07+00:00 172.18.0.1 api[1217]: Listening on http://1ea1b9232cea:4670/
2020-10-01T20:13:07+00:00 172.18.0.1 api[1217]: Hit Ctrl-C to quit.
2020-10-01T20:13:07+00:00 172.18.0.1 api[1217]: 
2020-10-01T20:13:07+00:00 172.18.0.1 api[1217]: <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
```
The fix is to hardcode greenlet version
```greenlet==0.4.16```

**Comment by jamadden** [comment] 2020-10-06 10:51
Thanks for the report, it's a duplicate of #178, among others. 

You can (should) also upgrade gevent to a version that supports 0.4.17.

**Closed by jamadden** 2020-10-06 10:51 UTC

**Comment by CrimsonGlory** [comment] 2020-10-06 15:57
Thanks. Upgrading gevent fixed the issue.
