### ISSUE TITLE
Support for AIX with XLC compiler

### ISSUE THREAD

**Issue by JordanStopford** [python-greenlet/greenlet#413] opened 2024-07-02 11:35 UTC
I've been playing around with trying to get this working but have hit upon a blocker with the assembler bits in greenlet, more specifically, not knowing what on earth it should be doing!

I can see there is support for gcc on AIX but none for XLC, so popping this in as a request. Happy to test any patches and report back

**Comment by jamadden** [comment] 2024-09-10 16:01
Closing as a duplicate of #118. PRs welcome.

**Closed by jamadden** 2024-09-10 16:01 UTC
Labels: Unsupported Platform, Help Wanted, Feature Request
