### ISSUE TITLE
Updating greenlet from v1.1.3 to v2.0.0 causes disk full on my uWSGI App

### ISSUE THREAD

**Issue by st2222** [python-greenlet/greenlet#351] opened 2023-02-28 07:32 UTC
After updating greenlet to v2.0.0, uWSGI App storage usage increases linearly, eventually causing disk full.
This phenomenon did not occur with greenlet v1.1.3
I can't figure out what changes in greenlet v2.0.0 caused the disk full.

- Application Info
    - Deploying Nginx + uWSGI + Flask Web Application on AWS ECS(fargate)
    - Python version: 3.9.16

- Load Test Settings
    - load test tool: locust
    - users: 50user
    - test time: 2h
    - RPS: 15.0

- Python libraries in myapp:
    - greenlet=2.0.0
    - uwsgi=2.0.21
    - flask=2.0.1
    - sqlalchemy=1.4.40

Here is an excerpt from the poetry.lock file when the error occurs:

```
[[package]]
name = "greenlet"
version = "2.0.0"
description = "Lightweight in-process concurrent programming"
category = "main"
optional = false
python-versions = ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*"

[[package]]
name = "uwsgi"
version = "2.0.21"
description = "The uWSGI server"
category = "main"
optional = false
python-versions = "*"

[[package]]
name = "Flask"
version = "2.0.1"
description = "A simple framework for building complex web applications."
category = "main"
optional = false
python-versions = ">=3.6"

[[package]]
name = "SQLAlchemy"
version = "1.4.40"
description = "Database Abstraction Library"
category = "main"
optional = false
python-versions = "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*,>=2.7"
```

**Comment by stianjensen** [comment] 2023-03-29 22:10
Been observing the same issue for the past week (since upgrading greenlet as part of a transitive dependency under bpython). We run a Django application with uwsgi, and have seen the disk slowly filling up with 'core dump' files from uwsgi of about 350MB each – each core dump being created upon shutdown of an uwsgi worker (which we have uwsgi periodically do).

The workers crash during shutdown with the message "Accessing state after destruction."

**Comment by stianjensen** [comment] 2023-05-30 16:45
Some extra context for my case, is that we're using Celery which is what is initializing inside our uwsgi workers. We have greenlet installed for an unrelated reason, but Celery imports greenlet as long as it's available (https://github.com/celery/celery/discussions/8169).

Unless Celery is doing something weird that's not compatible with greenlet 2.x, I still think there's some sort of regression that's caused this issue in 2.x ? It seems like there were other similar issues during shutdown that we're fixed in the RC stage, so that seems plausible.

**Closed** 2023-06-20 15:16 UTC
